#!/usr/bin/python3
import sys
import math

if len(sys.argv) < 2:
    print("Error: file name needed")
    exit(1)

try:
    reader = open(sys.argv[1], 'r')
except:
    print("Error: file not found")
    exit(1)

lines = reader.read(-1)
arr = lines.split("\n")

for i, n in enumerate(arr):
    try:
        arr[i] = int(n)
    except:
        del arr[i]

for n in arr:
    if n == 2:
        printf("2=2*1")
    elif n % 2 == 0:
        print(f"{n}={int(n/2)}*2")
    else:
        max_div = math.isqrt(n) + 1
        for i in range(3, int(max_div), 2):
            if n % i == 0:
                break
        if n % i == 0:
            print(f"{n}={int(n/i)}*{i}")
        else:
            print(f"{n}={n}*1")
